### PR TITLE
Add requirement for gawk to readme

### PR DESCRIPTION
**Pull request by hughdavenport**

### CODE REVIEW

**Comment by liancheng** [comment]
Thanks for the notes. It helped me to fix the scrolling issue under Mac OS X :)

One minor comment is that this fix is Mac specific while this plugin is not. Might be better to have it in a separate Mac specific sub-section?

**Comment by hughdavenport** [comment]
Hows that?

**Comment by NHDaly** [comment]
Thanks for the PR, @hughdavenport. :) Hopefully we've addressed this requirement in #13 and 5c94ada. If not, we can look at this PR again. :)

**Comment by NHDaly** [comment]
Yep, it looks like this isn't needed anymore since I think we've fixed the gawk issue finally. Thanks again!

**Pull request closed without merging**
